# Generated by Django 6.0.3 on 2026-04-16 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopiaChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('disponivel', 'Disponivel'), ('emprestada', 'Emprestada'), ('inativa', 'Inativa')], help_text='Status da copia da chave', max_length=15, verbose_name='Status')),
                ('emergencia', models.BooleanField(default=False, help_text='Indica se e copia de emergencia', verbose_name='Emergencia')),
                ('chave', models.ForeignKey(help_text='Chave de origem da copia', on_delete=django.db.models.deletion.CASCADE, related_name='copias', to='chaves.chave', verbose_name='Chave')),
            ],
            options={
                'verbose_name': 'Copia de Chave',
                'verbose_name_plural': 'Copias de Chave',
                'db_table': 'copias_copiachave',
            },
        ),
    ]
