# Generated by Django 6.0.3 on 2026-04-28 18:09

from django.db import migrations
from django.db import connection


def rename_copiachave_table(apps, schema_editor):
    tables = connection.introspection.table_names()
    if 'controle_copiachave' in tables and 'copias_copiachave' not in tables:
        schema_editor.execute("ALTER TABLE controle_copiachave RENAME TO copias_copiachave;")


def reverse_rename_copiachave_table(apps, schema_editor):
    tables = connection.introspection.table_names()
    if 'copias_copiachave' in tables and 'controle_copiachave' not in tables:
        schema_editor.execute("ALTER TABLE copias_copiachave RENAME TO controle_copiachave;")


class Migration(migrations.Migration):

    dependencies = [
        ('copias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copiachave',
            options={'verbose_name': 'Copia de Chave', 'verbose_name_plural': 'Copias de Chave'},
        ),
        migrations.RunPython(rename_copiachave_table, reverse_rename_copiachave_table),
    ]
