# Generated by Django 6.0.3 on 2026-04-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(help_text='Endereco do predio', max_length=255, verbose_name='Endereco')),
            ],
            options={
                'verbose_name': 'Predio',
                'verbose_name_plural': 'Predios',
                'db_table': 'predios_predio',
            },
        ),
    ]
