# Generated by Django 6.0.3 on 2026-04-28 18:09

from django.db import migrations
from django.db import connection


def rename_predio_table(apps, schema_editor):
    tables = connection.introspection.table_names()
    if 'controle_predio' in tables and 'predios_predio' not in tables:
        schema_editor.execute("ALTER TABLE controle_predio RENAME TO predios_predio;")


def reverse_rename_predio_table(apps, schema_editor):
    tables = connection.introspection.table_names()
    if 'predios_predio' in tables and 'controle_predio' not in tables:
        schema_editor.execute("ALTER TABLE predios_predio RENAME TO controle_predio;")


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predio',
            options={'verbose_name': 'Predio', 'verbose_name_plural': 'Predios'},
        ),
        migrations.RunPython(rename_predio_table, reverse_rename_predio_table),
    ]
