# Generated by Django 6.0.3 on 2026-04-16 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predio', models.ForeignKey(help_text='Predio ao qual a sala pertence', on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='predios.predio', verbose_name='Predio')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'db_table': 'salas_sala',
            },
        ),
        migrations.CreateModel(
            name='SalaComunitaria',
            fields=[
                ('sala_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='salas.sala')),
            ],
            options={
                'verbose_name': 'Sala Comunitaria',
                'verbose_name_plural': 'Salas Comunitarias',
                'db_table': 'salas_salacomunitaria',
            },
            bases=('salas.sala',),
        ),
        migrations.CreateModel(
            name='SalaExclusiva',
            fields=[
                ('sala_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='salas.sala')),
            ],
            options={
                'verbose_name': 'Sala Exclusiva',
                'verbose_name_plural': 'Salas Exclusivas',
                'db_table': 'salas_salaexclusiva',
            },
            bases=('salas.sala',),
        ),
    ]
