# Generated by Django 6.0.3 on 2026-04-28 18:09

from django.db import migrations
from django.db import connection


def rename_salas_tables_if_needed(apps, schema_editor):
    tables = connection.introspection.table_names()
    # Sala
    if 'controle_sala' in tables and 'salas_sala' not in tables:
        schema_editor.execute("ALTER TABLE controle_sala RENAME TO salas_sala;")
    # SalaComunitaria
    if 'controle_salacomunitaria' in tables and 'salas_salacomunitaria' not in tables:
        schema_editor.execute("ALTER TABLE controle_salacomunitaria RENAME TO salas_salacomunitaria;")
    # SalaExclusiva
    if 'controle_salaexclusiva' in tables and 'salas_salaexclusiva' not in tables:
        schema_editor.execute("ALTER TABLE controle_salaexclusiva RENAME TO salas_salaexclusiva;")


def reverse_rename_salas_tables_if_needed(apps, schema_editor):
    tables = connection.introspection.table_names()
    if 'salas_sala' in tables and 'controle_sala' not in tables:
        schema_editor.execute("ALTER TABLE salas_sala RENAME TO controle_sala;")
    if 'salas_salacomunitaria' in tables and 'controle_salacomunitaria' not in tables:
        schema_editor.execute("ALTER TABLE salas_salacomunitaria RENAME TO controle_salacomunitaria;")
    if 'salas_salaexclusiva' in tables and 'controle_salaexclusiva' not in tables:
        schema_editor.execute("ALTER TABLE salas_salaexclusiva RENAME TO controle_salaexclusiva;")


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sala',
            options={'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.RunPython(rename_salas_tables_if_needed, reverse_rename_salas_tables_if_needed),
        migrations.AlterModelOptions(
            name='salacomunitaria',
            options={'verbose_name': 'Sala Comunitaria', 'verbose_name_plural': 'Salas Comunitarias'},
        ),
        migrations.AlterModelOptions(
            name='salaexclusiva',
            options={'verbose_name': 'Sala Exclusiva', 'verbose_name_plural': 'Salas Exclusivas'},
        ),
    ]
