# Generated by Django 6.0.3 on 2026-04-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do usuario', max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(help_text='Email do usuario', max_length=254, unique=True, verbose_name='Email')),
                ('tipo', models.CharField(choices=[('administrador', 'Administrador'), ('usuario_normal', 'Usuario normal')], help_text='Tipo de usuario', max_length=20, verbose_name='Tipo')),
                ('senha', models.CharField(help_text='Senha do usuario', max_length=128, verbose_name='Senha')),
                ('cpf', models.CharField(help_text='CPF do usuario', max_length=14, unique=True, verbose_name='CPF')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios_usuario',
            },
        ),
    ]