# Generated by Django 6.0.3 on 2026-04-16 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salas', '0001_initial'),
        ('predios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sala', 'Chave de sala'), ('predio', 'Chave de predio')], default='sala', help_text='Define se a chave pertence a sala ou ao predio', max_length=10, verbose_name='Tipo')),
                ('sala', models.ForeignKey(blank=True, help_text='Sala da chave', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chaves', to='salas.sala', verbose_name='Sala')),
                ('predio', models.ForeignKey(blank=True, help_text='Predio da chave quando for chave geral', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chaves_predio', to='predios.predio', verbose_name='Predio')),
            ],
            options={
                'verbose_name': 'Chave',
                'verbose_name_plural': 'Chaves',
                'db_table': 'chaves_chave',
            },
        ),
    ]
