# Generated by Django 6.0.3 on 2026-04-28 18:09

from django.db import migrations
from django.db import connection


def rename_chave_table(apps, schema_editor):
    tables = connection.introspection.table_names()
    if 'controle_chave' in tables and 'chaves_chave' not in tables:
        schema_editor.execute("ALTER TABLE controle_chave RENAME TO chaves_chave;")


def reverse_rename_chave_table(apps, schema_editor):
    tables = connection.introspection.table_names()
    if 'chaves_chave' in tables and 'controle_chave' not in tables:
        schema_editor.execute("ALTER TABLE chaves_chave RENAME TO controle_chave;")


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chave',
            options={'verbose_name': 'Chave', 'verbose_name_plural': 'Chaves'},
        ),
        migrations.RunPython(rename_chave_table, reverse_rename_chave_table),
    ]
