# Generated by Django 6.0.3

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0003_add_sala_state'),
    ]

    operations = [
    ]
