# Generated by Django 6.0.3 on 2026-05-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0004_chave_predio_chave_tipo_alter_chave_sala'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chave',
            options={'ordering': ['id'], 'verbose_name': 'Chave', 'verbose_name_plural': 'Chaves'},
        ),
    ]
