# Generated by Django 6.0.3 on 2026-04-28 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('copias', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateField(help_text='Data de retirada da chave', verbose_name='Data de retirada')),
                ('data_prevista', models.DateField(help_text='Data prevista de devolucao', verbose_name='Data prevista')),
                ('data_devolucao', models.DateField(blank=True, help_text='Data efetiva de devolucao', null=True, verbose_name='Data de devolucao')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('devolvido', 'Devolvido'), ('atrasado', 'Atrasado')], help_text='Status do emprestimo', max_length=15, verbose_name='Status')),
                ('copia_chave', models.ForeignKey(help_text='Copia de chave emprestada', on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='copias.copiachave', verbose_name='Copia da chave')),
                ('reserva', models.OneToOneField(blank=True, help_text='Reserva que originou o emprestimo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimo', to='reservas.reserva', verbose_name='Reserva')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizou o emprestimo', on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='usuarios.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
            },
        ),
    ]
