# Generated by Django 6.0.3 on 2026-05-06 18:13

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': [django.db.models.functions.text.Upper('usuario__nome')], 'verbose_name': 'Emprestimo', 'verbose_name_plural': 'Emprestimos'},
        ),
    ]
