# Generated by Django 6.0.3 on 2026-04-16 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('copias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data da reserva', verbose_name='Data')),
                ('horario', models.TimeField(help_text='Horario da reserva', verbose_name='Horario')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], help_text='Status da reserva', max_length=15, verbose_name='Status')),
                ('usuario', models.ForeignKey(help_text='Usuario da reserva', on_delete=django.db.models.deletion.CASCADE, related_name='reservas_modulo', to='usuarios.usuario', verbose_name='Usuario')),
                ('copia_chave', models.ForeignKey(blank=True, help_text='Copia de chave vinculada a reserva', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='copias.copiachave', verbose_name='Copia da chave')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas_reserva',
            },
        ),
    ]
