# Generated by Django 6.0.3 on 2026-04-28 18:09

from django.db import migrations
from django.db import connection


def rename_reserva_table(apps, schema_editor):
    tables = connection.introspection.table_names()
    if 'controle_reserva' in tables and 'reservas_reserva' not in tables:
        schema_editor.execute("ALTER TABLE controle_reserva RENAME TO reservas_reserva;")


def reverse_rename_reserva_table(apps, schema_editor):
    tables = connection.introspection.table_names()
    if 'reservas_reserva' in tables and 'controle_reserva' not in tables:
        schema_editor.execute("ALTER TABLE reservas_reserva RENAME TO controle_reserva;")


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.RunPython(rename_reserva_table, reverse_rename_reserva_table),
    ]
